# 提交代码git push时，触发下面的操作
kind: pipeline
name: push

steps:
  - name: error_code-analysis #代码质量检测
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host: https://sonar.xxx.com
      sonar_token: xxxxxxxxxx #在sonar.xxxxxx.com中生成，生成过程见文档下方

trigger: #这个pipeline触发的条件：git push的分支是master时才运行
  branch:
    - master

---
#需要自动部署时触发，必须发布git tag
kind: pipeline
name: release
steps:
  - name: build-server
    image: golang:1.13.0-buster
    commands:
      #      - go env -w GOPROXY=https://goproxy.cn,direct
      #      - go env -w GOPRIVATE=hub.xxxxxx.com,git.xxxxxx.com,git.xxxx.com
      #      - go test -mod=vendor
      - go build -mod=vendor -ldflags="-s -w" -o bin/bin_tmp/go-web-demo
      - cp -r config/ bin/
    environment:
      GOPATH: /drone/src/go
  #
  #  - name: build-image
  #    image: plugins/docker
  #    settings:
  #      repo: docker.xxxxxx.cn:8066/micro-services
  #      username: admin
  #      password:
  #        from_secret: Abcd1234
  #      auto_tag: true

  - name: release #版本构建
    image: koyo/drone-release
    settings:
      base_url: https://minio.xxxxxx.com/project-701
      dir: bin/
      rectify_commit: true
      token:
        from_secret: go-web-demo #在持续集成后台配置的Secret Name是什么就填什么


trigger:
  event: tag